--Change format
column OWNER format  'a15';
column CONSTRAINT_NAME format  'a15';
column TABLE_NAME format 'a15';
column SEARCH_CONDITION format 'a15';
column INDEX_NAME format 'a15';

--Question1.1
SELECT OWNER, CONSTRAINT_NAME, TABLE_NAME, SEARCH_CONDITION, INDEX_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('DEPT','EMP','PURCHASE','CLIENT');

--Question1.2
ALTER TABLE PURCHASE ADD CONSTRAINT PK_PURCHASENO PRIMARY KEY (PURCHASENO);
ALTER TABLE DEPT ADD CONSTRAINT UN_DNAME UNIQUE (DName);
ALTER TABLE EMP ADD CONSTRAINT CK_ENAME CHECK (ENAME IS NOT NULL);
ALTER TABLE DEPT ADD CONSTRAINT CK_DNAME CHECK (DNAME IS NOT NULL);
ALTER TABLE CLIENT ADD CONSTRAINT CK_CNAME CHECK (CName IS NOT NULL);
ALTER TABLE PURCHASE ADD CONSTRAINT CK_RECEIPTNO CHECK (ReceiptNo IS NOT NULL);
ALTER TABLE PURCHASE ADD CONSTRAINT CK_AMOUNT CHECK (Amount > 0);
ALTER TABLE EMP ADD CONSTRAINT CK_POSITION CHECK (Position IN ('Group Manager', 'Group Assistant', 'Group Member', 'Team Leader', 'Branch Manager'));
ALTER TABLE PURCHASE ADD CONSTRAINT CK_SERVICETYPE CHECK (ServiceType IN ('Software Installation', 'Software Repair', 'Training', 'Consultation', 'Data Recovery'));
ALTER TABLE PURCHASE ADD CONSTRAINT CK_PAYMENTTYPE CHECK (PaymentType IN ('Debit', 'Cash', 'Credit'));
ALTER TABLE PURCHASE ADD CONSTRAINT CK_GST CHECK (GST IN ('Yes', 'No'));
ALTER TABLE EMP ADD CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO);
ALTER TABLE PURCHASE ADD CONSTRAINT FK_EMPNO FOREIGN KEY (ServedBy) REFERENCES EMP (EMPNO);
ALTER TABLE PURCHASE ADD CONSTRAINT FK_CLIENTNO FOREIGN KEY (ClientNo) REFERENCES CLIENT (ClientNo);

--Question 2.1
--Drop the sequence before creating one
DROP SEQUENCE PNO_SEQ;
CREATE SEQUENCE "PNO_SEQ" MINVALUE 10000 MAXVALUE 9999999999999 INCREMENT BY 1 START WITH 10000;

--Question 2.2
CREATE OR REPLACE TRIGGER "BI_PNO"
 BEFORE INSERT ON "PURCHASE"
 FOR EACH ROW
BEGIN
 SELECT "PNO_SEQ".NEXTVAL INTO :NEW.PURCHASENO FROM DUAL;
END;
/

--Question 2.3
CREATE TRIGGER "TOP_DISCOUNT"
	BEFORE INSERT ON "PURCHASE"
	FOR EACH ROW
DECLARE 
	top_amount NUMBER;
	new_client_total_amount NUMBER;
BEGIN 
	SELECT MAX(SUM(Amount))
	INTO top_amount
	FROM PURCHASE
	GROUP BY ClientNo;

	SELECT SUM(Amount) 
	INTO new_client_total_amount
	FROM PURCHASE
	WHERE PURCHASE.CLIENTNO = :NEW.CLIENTNO
	GROUP BY ClientNo;

	IF (top_amount = new_client_total_amount) THEN
		:NEW.Amount := :NEW.Amount*(1-0.15);
	END IF;
END;
/

--Question 2.4
CREATE TRIGGER "SUNSHINE_DEPT"
	BEFORE INSERT ON "PURCHASE"
	FOR EACH ROW
DECLARE 
	purchase_dept VARCHAR2(20);
BEGIN
	SELECT DName 
    INTO purchase_dept 
    FROM EMP, DEPT 
    WHERE EMP.EmpNo = :NEW.ServedBy AND EMP.DeptNo = DEPT.DeptNo;
	IF (purchase_dept = 'SALES - Sunshine') THEN
		:NEW.PaymentType := 'Cash';
        IF (:NEW.ServiceType = 'Data Recovery') THEN
            :NEW.Amount := :NEW.Amount*(1-0.3);
        END IF;
	END IF;
END;
/


